require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PossessionsController do

  # This should return the minimal set of attributes required to create a valid
  # Possession. As you add validations to Possession, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all possessions as @possessions" do
      possession = Possession.create! valid_attributes
      get :index
      assigns(:possessions).should eq([possession])
    end
  end

  describe "GET show" do
    it "assigns the requested possession as @possession" do
      possession = Possession.create! valid_attributes
      get :show, :id => possession.id.to_s
      assigns(:possession).should eq(possession)
    end
  end

  describe "GET new" do
    it "assigns a new possession as @possession" do
      get :new
      assigns(:possession).should be_a_new(Possession)
    end
  end

  describe "GET edit" do
    it "assigns the requested possession as @possession" do
      possession = Possession.create! valid_attributes
      get :edit, :id => possession.id.to_s
      assigns(:possession).should eq(possession)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Possession" do
        expect {
          post :create, :possession => valid_attributes
        }.to change(Possession, :count).by(1)
      end

      it "assigns a newly created possession as @possession" do
        post :create, :possession => valid_attributes
        assigns(:possession).should be_a(Possession)
        assigns(:possession).should be_persisted
      end

      it "redirects to the created possession" do
        post :create, :possession => valid_attributes
        response.should redirect_to(Possession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved possession as @possession" do
        # Trigger the behavior that occurs when invalid params are submitted
        Possession.any_instance.stub(:save).and_return(false)
        post :create, :possession => {}
        assigns(:possession).should be_a_new(Possession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Possession.any_instance.stub(:save).and_return(false)
        post :create, :possession => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested possession" do
        possession = Possession.create! valid_attributes
        # Assuming there are no other possessions in the database, this
        # specifies that the Possession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Possession.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => possession.id, :possession => {'these' => 'params'}
      end

      it "assigns the requested possession as @possession" do
        possession = Possession.create! valid_attributes
        put :update, :id => possession.id, :possession => valid_attributes
        assigns(:possession).should eq(possession)
      end

      it "redirects to the possession" do
        possession = Possession.create! valid_attributes
        put :update, :id => possession.id, :possession => valid_attributes
        response.should redirect_to(possession)
      end
    end

    describe "with invalid params" do
      it "assigns the possession as @possession" do
        possession = Possession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Possession.any_instance.stub(:save).and_return(false)
        put :update, :id => possession.id.to_s, :possession => {}
        assigns(:possession).should eq(possession)
      end

      it "re-renders the 'edit' template" do
        possession = Possession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Possession.any_instance.stub(:save).and_return(false)
        put :update, :id => possession.id.to_s, :possession => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested possession" do
      possession = Possession.create! valid_attributes
      expect {
        delete :destroy, :id => possession.id.to_s
      }.to change(Possession, :count).by(-1)
    end

    it "redirects to the possessions list" do
      possession = Possession.create! valid_attributes
      delete :destroy, :id => possession.id.to_s
      response.should redirect_to(possessions_url)
    end
  end

end
